#pragma once

#include <stdint.h>
#include "sdkconfig.h"

#ifdef CONFIG_IDF_TARGET_ESP32C6
#define LOSCFG_ARCH_RISCV32 1
#define LOSCFG_ARCH_CPU "rv32imac"
#else
#define LOSCFG_ARCH_XTENSA 1
#define LOSCFG_ARCH_CPU "xtensa"
#endif

#define LOSCFG_COMPILER_GCC 1
#define LOSCFG_PLATFORM_HWI 0
#define LOSCFG_USE_SYSTEM_DEFINED_INTERRUPT 0
#define LOSCFG_PLATFORM_HWI_LIMIT 32
#define LOSCFG_BASE_CORE_TICK_PER_SECOND CONFIG_OHOS_TICK_HZ
#define LOSCFG_BASE_CORE_TICK_WTIMER 1
#define LOSCFG_BASE_CORE_TICK_RESPONSE_MAX UINT64_MAX

#define LOSCFG_BASE_CORE_TSK_LIMIT 8
#define LOSCFG_BASE_CORE_TSK_MIN_STACK_SIZE 0x200
#define LOSCFG_BASE_CORE_TSK_DEFAULT_STACK_SIZE 0x1000
#define LOSCFG_BASE_CORE_TSK_IDLE_STACK_SIZE 0x800
#define LOSCFG_BASE_CORE_TIMESLICE 1
#define LOSCFG_BASE_CORE_TSK_MONITOR 0
#define LOSCFG_BASE_CORE_EXC_TSK_SWITCH 0
#define LOSCFG_BASE_CORE_TASKSTACK_INDEPENDENT 0

#define LOSCFG_BASE_IPC_SEM 1
#define LOSCFG_BASE_IPC_SEM_LIMIT 16
#define LOSCFG_BASE_IPC_MUX 1
#define LOSCFG_BASE_IPC_MUX_LIMIT 16
#define LOSCFG_BASE_IPC_QUEUE 1
#define LOSCFG_BASE_IPC_QUEUE_LIMIT 8
#define LOSCFG_BASE_IPC_STATIC_QUEUE_LIMIT 0

#define LOSCFG_BASE_CORE_SWTMR 1
#define LOSCFG_BASE_CORE_SWTMR_LIMIT 8
#define LOSCFG_BASE_CORE_SWTMR_ALIGN 0

#define LOSCFG_SYS_EXTERNAL_HEAP 0
#define LOSCFG_SYS_HEAP_SIZE CONFIG_OHOS_PORT_HEAP_FALLBACK_SIZE
#define LOSCFG_MEM_MUL_POOL 0
#define LOSCFG_MEM_FREE_BY_TASKID 0
#define LOSCFG_BASE_MEM_NODE_INTEGRITY_CHECK 0
#define LOSCFG_MEM_WATERLINE 0
#define LOSCFG_MEM_LEAKCHECK_RECORD_MAX_NUM 32

#define LOSCFG_PLATFORM_EXC 0
#define LOSCFG_BACKTRACE_TYPE 0
#define LOSCFG_BASE_CORE_CPUP 0
#define LOSCFG_CPUP_INCLUDE_IRQ 0
#define LOSCFG_KERNEL_PM 0
#define LOSCFG_KERNEL_LMK 0
#define LOSCFG_DYNLINK 0
#define LOSCFG_POSIX_PIPE_API 0
#define LOSCFG_KERNEL_SIGNAL 0
#define LOSCFG_SECURE 0
#define LOSCFG_FS_VFS 0
#define LOSCFG_KERNEL_TRACE 0
#define LOSCFG_KERNEL_PRINTF 1
#define LOSCFG_MPU_ENABLE 0
#define LOSCFG_TASK_MEM_USED 0
#define LOSCFG_PLATFORM_HWI_WITH_ARG 0
#define LOSCFG_ARCH_HWI_VECTOR_ALIGN 0x100
